const SEED_INQUIRIES = [
  {
    inquiryType: 'Project Assessment',
    name: 'James Wilson',
    organization: 'Wilson Global Advisory',
    role: 'Managing Director',
    phone: '+1 202 555 0145',
    email: 'james@example.com',
    project: 'Mission Critical Modernization',
    context: 'Comprehensive audit and readiness assessment for executive portfolio transformation.',
    message: 'I would like to learn more about the LMCS framework and arrange a consultation.',
    status: 'New',
    subject: 'Consultation Request',
  },
  {
    inquiryType: 'Executive / Portfolio',
    name: 'Sarah Miller',
    organization: 'Apex Core Solutions',
    role: 'Chief Risk Officer',
    phone: '+1 202 555 0188',
    email: 'sarah@example.com',
    project: 'Portfolio Governance Overhaul',
    context: 'Aligning cross-discipline delivery confidence metrics across tier-1 infrastructure projects.',
    message: 'Could you provide more information about your executive advisory services?',
    status: 'Read',
    subject: 'Website Inquiry',
  },
  {
    inquiryType: 'General Inquiry',
    name: 'Michael Brown',
    organization: 'Beacon Systems',
    role: 'Director of Infrastructure',
    phone: '+1 202 555 0132',
    email: 'michael@example.com',
    project: 'General Inquiries',
    context: 'Preliminary scoping regarding external audit standards and frameworks.',
    message: 'I have a question regarding your services.',
    status: 'Closed',
    subject: 'General Question',
  },
  {
    inquiryType: 'Partnership',
    name: 'Emily Carter',
    organization: 'Carter & Associates',
    role: 'VP Strategy & Alliances',
    phone: '+1 202 555 0117',
    email: 'emily.carter@example.com',
    project: 'Joint Advisory Framework',
    context: 'Exploring synergistic partnerships in mission-critical environments.',
    message: 'Our firm is interested in exploring a partnership with LMCS for joint advisory engagements.',
    status: 'New',
    subject: 'Partnership Opportunity',
  },
  {
    inquiryType: 'Atlas Platform',
    name: 'David Thompson',
    organization: 'Titan Infrastructure Group',
    role: 'Head of Operations',
    phone: '+1 202 555 0166',
    email: 'd.thompson@example.com',
    project: 'ATLAS Intelligence Integration',
    context: 'Platform rollout assessment for real-time telemetry and site intelligence.',
    message: 'Is it possible to schedule a demo of the ATLAS assessment framework for our leadership team?',
    status: 'New',
    subject: 'ATLAS Framework Demo',
  },
  {
    inquiryType: 'Practitioner',
    name: 'Laura Chen',
    organization: 'Global Tech Summit',
    role: 'Program Director',
    phone: '+1 202 555 0198',
    email: 'laura.chen@example.com',
    project: 'Annual Operations Summit',
    context: 'Practitioner track keynote and methodology workshops.',
    message: "We'd like to invite a member of your team to speak at our upcoming operations summit.",
    status: 'Read',
    subject: 'Speaking Engagement',
  },
  {
    inquiryType: 'Project Assessment',
    name: 'Robert Kim',
    organization: 'Northeastern Rail & Power',
    role: 'VP Capital Projects',
    phone: '+1 202 555 0121',
    email: 'robert.kim@example.com',
    project: 'Delivery Confidence Track',
    context: 'Pre-construction confidence rating and drift mitigation review.',
    message: 'Could you send over pricing information for the Delivery Confidence engagement track?',
    status: 'Closed',
    subject: 'Pricing Question',
  },
  {
    inquiryType: 'General Inquiry',
    name: 'Nina Patel',
    organization: 'Infrastructure Insights Media',
    role: 'Senior Editor',
    phone: '+1 202 555 0154',
    email: 'nina.patel@example.com',
    project: 'Resilience Feature Series',
    context: 'Editorial interview on high-consequence system failures and leadership.',
    message: "I'm writing a feature on organizational resilience and would like a brief interview.",
    status: 'New',
    subject: 'Media Request',
  },
  {
    inquiryType: 'Atlas Platform',
    name: 'Marcus Vance',
    organization: 'Vance Cybernetics',
    role: 'Chief Security Architect',
    phone: '+1 202 555 0177',
    email: 'm.vance@example.com',
    project: 'Autonomous Site Telemetry',
    context: 'Zero-trust integration and mission-critical site monitoring.',
    message: 'Seeking technical architectural documentation for ATLAS deployment.',
    status: 'Read',
    subject: 'Technical Scoping',
  },
  {
    inquiryType: 'Executive / Portfolio',
    name: 'Elena Rostova',
    organization: 'Crestview Holdings',
    role: 'Managing Partner',
    phone: '+1 202 555 0109',
    email: 'e.rostova@example.com',
    project: 'Portfolio Stress Test',
    context: 'Comprehensive risk audit across 14 high-stakes asset deployments.',
    message: 'Requesting a confidential briefing on delivery-confidence methodology.',
    status: 'Closed',
    subject: 'Confidential Briefing',
  },
];

module.exports = {
  SEED_INQUIRIES,
};
